/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ComponentOne {
        "color": string;
    }
    interface ComponentTwo {
        "color": string;
    }
    interface TooltipParent {
        "color": string;
    }
}
declare global {
    interface HTMLComponentOneElement extends Components.ComponentOne, HTMLStencilElement {
    }
    var HTMLComponentOneElement: {
        prototype: HTMLComponentOneElement;
        new (): HTMLComponentOneElement;
    };
    interface HTMLComponentTwoElement extends Components.ComponentTwo, HTMLStencilElement {
    }
    var HTMLComponentTwoElement: {
        prototype: HTMLComponentTwoElement;
        new (): HTMLComponentTwoElement;
    };
    interface HTMLTooltipParentElement extends Components.TooltipParent, HTMLStencilElement {
    }
    var HTMLTooltipParentElement: {
        prototype: HTMLTooltipParentElement;
        new (): HTMLTooltipParentElement;
    };
    interface HTMLElementTagNameMap {
        "component-one": HTMLComponentOneElement;
        "component-two": HTMLComponentTwoElement;
        "tooltip-parent": HTMLTooltipParentElement;
    }
}
declare namespace LocalJSX {
    interface ComponentOne {
        "color"?: string;
    }
    interface ComponentTwo {
        "color"?: string;
    }
    interface TooltipParent {
        "color"?: string;
    }
    interface IntrinsicElements {
        "component-one": ComponentOne;
        "component-two": ComponentTwo;
        "tooltip-parent": TooltipParent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "component-one": LocalJSX.ComponentOne & JSXBase.HTMLAttributes<HTMLComponentOneElement>;
            "component-two": LocalJSX.ComponentTwo & JSXBase.HTMLAttributes<HTMLComponentTwoElement>;
            "tooltip-parent": LocalJSX.TooltipParent & JSXBase.HTMLAttributes<HTMLTooltipParentElement>;
        }
    }
}
